# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87102140e06e91b61e86ef0cbda23904ebf77fc365a0c5b2610044934cef67092663f719a5137d56ca55f35236e8ac714706e5e765dce2c52ad2b9c64b76e3c8

test:
  secret_key_base: 0d71dd728d63744680ade256bb465d1f90f1f11c142c56133b4e56cc135269a96cf59ee71e2494bd4e72a573dc852ac9ff5b3b7a9e42111bb85336dbb786bc5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
